---
- hosts: DEV
  connection: ssh

  vars:
    abc: "git"
    xyz: "maven"
  tasks:
    - name: I'm installing scm/vcs on this server
      action: yum name={{abc}}  state=absent

    - name: Im installing build tool on this server
      action: yum name={{xyz}} state=absent
...
